---
- name: Copy Private Deployment-Key
  copy:
    src: "{{ deployment_src_path }}{{ deployment_key_name_private }}"
    dest: "{{ deployment_key_destination_path_ssh_user }}{{ deployment_key_name_private }}"
    owner: "{{ deployment_ssh_user }}"
    group: www-data
    mode: u=r,g=,o=
  become: yes

- name: Copy Public Deployment-Key
  copy:
    src: "{{ deployment_src_path }}{{ deployment_key_name_public }}"
    dest: "{{ deployment_key_destination_path_ssh_user }}{{ deployment_key_name_public }}"
    owner: "{{ deployment_ssh_user }}"
    group: www-data
    mode: u=rw,g=rw,o=r
  become: yes

- name: "create {{ deployment_auth_destination_path_ssh_user }} if it does not exist"
  file:
    state: directory
    path: "{{ deployment_auth_destination_path_ssh_user }}"
    owner: "{{ deployment_ssh_user }}"
    group: www-data
  become: yes

- name: "Store Toran-Authentication for composer installation for User {{ deployment_ssh_user }}"
  copy:
    src: "{{ deployment_src_path }}{{ deployment_name_of_toran_auth_file }}"
    dest: "{{ deployment_auth_destination_path_ssh_user }}/auth.json"
    owner: "{{ deployment_ssh_user }}"
    group: www-data
    mode: 0600
  become: yes
  when: deployment_install_composer_auth

- name: Copy Private Deployment-Key to root user if configured
  copy:
    src: "{{ deployment_src_path }}{{ deployment_key_name_private }}"
    dest: "{{ deployment_key_destination_path_root }}{{ deployment_key_name_private }}"
    owner: root
    group: root
    mode: u=r,g=,o=
  become: yes
  when: deployment_key_to_root_user
  notify: remove key from root

- name: Copy Public Deployment-Key to root user if configured
  copy:
    src: "{{ deployment_src_path }}{{ deployment_key_name_public }}"
    dest: "{{ deployment_key_destination_path_root }}{{ deployment_key_name_public }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: yes
  when: deployment_key_to_root_user
  notify: remove key from root

- name: Store Toran-Authentication for composer installation for User root
  copy:
    src: "{{ deployment_src_path }}{{ deployment_name_of_toran_auth_file }}"
    dest: /root/.composer/auth.json
    owner: root
    group: root
    mode: 0600
  become: yes
  when: deployment_install_composer_auth

- name: Copy Private Deployment-Key to www-data user
  copy:
    src: "{{ deployment_src_path }}{{ deployment_key_name_private }}"
    dest: "{{ deployment_key_destination_path }}{{ deployment_key_name_private }}"
    owner: www-data
    group: www-data
    mode: u=r,g=,o=
  become: yes

- name: Copy Public Deployment-Key to www-data user
  copy:
    src: "{{ deployment_src_path }}{{ deployment_key_name_public }}"
    dest: "{{ deployment_key_destination_path }}{{ deployment_key_name_public }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: yes
